#Take the Tomcat-9 image which supports AdoptOpenJDK
FROM tomcat:9.0.68-jdk8-temurin-jammy

#Copy the WAR file to tomcat
COPY ./target/demo.war /usr/local/tomcat/webapps/demo.war

#Allow execution (Not required, just added)
CMD chmod +x /usr/local/tomcat/bin/catalina.sh